program pepe;
var AA: integer;
       BB: boolean;
      B: integer;

procedure Algo(a: integer);
begin
   AA:= 666;
end;

procedure Algo2(par1,par2,par3,par4:integer; par5: boolean);
begin
    Algo(33);
     Algo2( 2,3,4,4,5>6);
     {Algo;  }
end;

procedure Algo3(par:integer);
var par4: integer;
begin
    Algo(par+1*AA+par4);
    par:= par+1*AA;
    BB:= par+1*AA > 55;

end;



begin
     BB:= 77+AA > 44;

          algo2( 2,3,4,4,5>6, 66);
  if AA > 7 then algo3(4 )
 else algo(88);

end.