Program ConductoDePrueba;
Var
  c,h,r: integer;
  r2:boolean;

procedure pru2(); 
{procedure pru2; }
var r22: integer;
begin
  PRu2();  {pru2();}  
  {pru:=18  }
  if r2 and false then  
  r := 4;
end;

Begin
  read(c);
  if (  ((c > -(5*4*r))) or (3<>5) ) then  
  if r2 then  
  if (  ((c > -(5*4*r))) or (3<>5) and true or r2 ) then  


  begin
     write(1);
  end
  else
     write(0);

End.
