lexema program, token('keyword','program')
lexema OperacionesBasicas, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
lexema var, token('keyword','var')
lexema numero1, token('id', 'puntero-a-ts')
lexema ,, token('coma', None)
lexema numero2, token('id', 'puntero-a-ts')
lexema ,, token('coma', None)
lexema suma, token('id', 'puntero-a-ts')
lexema ,, token('coma', None)
lexema resta, token('id', 'puntero-a-ts')
lexema ,, token('coma', None)
lexema multiplicacion, token('id', 'puntero-a-ts')
lexema ,, token('coma', None)
lexema division, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema integer, token('keyword','integer')
lexema ;, token('puntoComa', None)
lexema begin, token('keyword','begin')
token(None, None)
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Ingrese, token('id', 'puntero-a-ts')
lexema el, token('id', 'puntero-a-ts')
lexema primer, token('id', 'puntero-a-ts')
lexema numero, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema readln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
lexema numero1, token('id', 'puntero-a-ts')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Ingrese, token('id', 'puntero-a-ts')
lexema el, token('id', 'puntero-a-ts')
lexema segundo, token('id', 'puntero-a-ts')
lexema numero, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema readln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
lexema numero2, token('id', 'puntero-a-ts')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
token(None, None)
lexema suma, token('id', 'puntero-a-ts')
lexema :=, token('asignacion', None)
lexema numero1, token('id', 'puntero-a-ts')
lexema +, token('operadorAritmetico', 'suma')
lexema numero2, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
lexema resta, token('id', 'puntero-a-ts')
lexema :=, token('asignacion', None)
lexema numero1, token('id', 'puntero-a-ts')
lexema -, token('operadorAritmetico', 'resta')
lexema numero2, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
lexema multiplicacion, token('id', 'puntero-a-ts')
lexema :=, token('asignacion', None)
lexema numero1, token('id', 'puntero-a-ts')
lexema *, token('operadorAritmetico', 'multi')
lexema numero2, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
token(None, None)
lexema if, token('keyword','if')
lexema numero2, token('id', 'puntero-a-ts')
lexema <>, token('operadorRelacional', 'distinto')
lexema 0, token('enteroDato','0')
lexema then, token('keyword','then')
lexema division, token('id', 'puntero-a-ts')
lexema :=, token('asignacion', None)
lexema numero1, token('id', 'puntero-a-ts')
lexema /, token('operadorAritmetico', 'div')
lexema numero2, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
lexema else, token('keyword','else')
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Error, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema No, token('id', 'puntero-a-ts')
lexema se, token('id', 'puntero-a-ts')
lexema puede, token('id', 'puntero-a-ts')
lexema dividir, token('id', 'puntero-a-ts')
lexema por, token('id', 'puntero-a-ts')
lexema cero, token('id', 'puntero-a-ts')
token(None, None)
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
token(None, None)
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Suma, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ,, token('coma', None)
lexema suma, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema 0, token('enteroDato','0')
lexema :, token('dosPuntos', None)
lexema 2, token('enteroDato','2')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Resta, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ,, token('coma', None)
lexema resta, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema 0, token('enteroDato','0')
lexema :, token('dosPuntos', None)
lexema 2, token('enteroDato','2')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Multiplicacion, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ,, token('coma', None)
lexema multiplicacion, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema 0, token('enteroDato','0')
lexema :, token('dosPuntos', None)
lexema 2, token('enteroDato','2')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema if, token('keyword','if')
lexema numero2, token('id', 'puntero-a-ts')
lexema <>, token('operadorRelacional', 'distinto')
lexema 0, token('enteroDato','0')
lexema then, token('keyword','then')
lexema writeln, token('id', 'puntero-a-ts')
lexema (, token('parentesis', '(')
token(None, None)
lexema Division, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
token(None, None)
lexema ,, token('coma', None)
lexema division, token('id', 'puntero-a-ts')
lexema :, token('dosPuntos', None)
lexema 0, token('enteroDato','0')
lexema :, token('dosPuntos', None)
lexema 2, token('enteroDato','2')
lexema ), token('parentesis', ')')
lexema ;, token('puntoComa', None)
lexema readln, token('id', 'puntero-a-ts')
lexema ;, token('puntoComa', None)
token(None, None)
lexema end, token('keyword','end')
lexema ., token('punto', None)
